name: "Shared Tox"
description: |
  Invokes Tox using shared config.

  Pre-requires tox being installed.

inputs:
  tox-args:
    description: "Arguments to pass to tox"
    required: true
    type: string
  python-test-args:
    description: "What arguments to pass to python or coverage to run tests"
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Run tox
    run: tox -c ${{ github.action_path }}/tox-ci.ini ${{ inputs.tox-args }}
    shell: bash
    env:
      TOX_PROJECT_DIR: ${{ github.workspace }}
      TOX_PYTHON_TEST_ARGS: ${{ inputs.python-test-args }}
      RUN_PYFLAKES_BIN: ${{ github.action_path }}/run-pyflakes.sh
