name: "Shared Tox"
description: |
  Invokes Tox using shared config.

  Pre-requires tox being installed.

inputs:
  tox-args:
    description: "Arguments to pass to tox"
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Run tox
    run: tox -c ${{ github.action_path }}/tox-ci.ini ${{ inputs.args }}
    shell: bash
