name: "Install Tox"
description: Installs Python and tox

inputs:
  python-version:
    description: "Version of Python to install using actions/setup-python@2"
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}
      architecture: x64

  - name: Install tox
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install tox tox-gh-actions
