name: python-ci

on:
  workflow_call:
    inputs:
      util-python-version:
        description: "Which version of Python to use for coverage testing / linting"
        default: '3.9'
        required: false
        type: string
      coverage-tox-target:
        description: "Target to give to tox -e for running coverage"
        default: cover
        required: false
        type: string
      package-folder:
        description: "What folders contains the source of this package"
        required: true
        type: string

    secrets:
      delegate_github_token:
        required: true


jobs:
  test:
    name: "Run tests"
    runs-on: 'ubuntu-latest'
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version:
        - '3.5'
        - 'pypy3'
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        experimental:
        - false
        include:
        - python-version: '3.10-dev'
          experimental: true
        - python-version: '3.11-dev'
          experimental: true

    steps:
    - uses: ./.github/actions/install-tox.yaml
      with:
        python-version: ${{ inputs.util-python-version }}
    - name: Test with tox
      uses: ./.github/actions/tox-ci.yaml
      with:
        tox-args: ""
    - name: Verify that tox 'test' env ran
      run: cat ./tox-proof-test

  cover:
    name: "Report coverage"
    runs-on: 'ubuntu-latest'
    steps:
    - env:
        GHAENV: ${{ toJSON(github.event) }}
      run: |
      echo $GHAENV
    - uses: ./.github/actions/install-tox.yaml
      with:
        python-version: ${{ inputs.util-python-version }}
    - name: Gather coverage with tox
      uses: ./.github/actions/tox-ci.yaml
      with:
        tox-args: -e ${{ inputs.coverage-tox-target }}
    - name: Verify that tox 'cover' env ran
      run: cat ./tox-proof-cover
    - name: 'Report coverage'
      uses: ./.github/actions/tox-ci.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.delegate_github_token }}
      with:
        tox-args: -e coveralls-gh-actions

  lint:
    name: "Run lint"
    runs-on: 'ubuntu-latest'
    steps:
    - uses: ./.github/actions/install-tox.yaml
      with:
        python-version: ${{ inputs.util-python-version }}
    - name: Run linter with tox
      uses: ./.github/actions/tox-ci.yaml
      with:
        python-version: ${{ inputs.util-python-version }}
        tox-args: -e pyflakes
